### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by marineb** [DISIC/design.numerique.gouv.fr#8]
- [ ] Exemple decl accessibilité
- [ ] Expliquer relation WCAG, norme EU, et RGAA
- [ ] Partager des stats d'usage ex : https://www.acsel.eu/wp-content/uploads/2020/02/Infographie-des-10-ans-Barom%C3%A8tre-confiance-ACSEL.pdf
- [ ] Ajouter des references de livres a lire
- [ ] Exemple schema pluriannuel
